### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.compute_overlap'

### ISSUE THREAD

**Issue by jewelc92** [xuannianz/keras-fcos#1]
楼主，按你给的train命令会报如下错误：
File "/keras-fcos-master/utils/anchors.py", line 4, in <module>
    from utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'utils.compute_overlap'

**Comment by xuannianz** [comment]
@jewelc92 你好，我刚上传了 compute_overlap 模块，你下载一下试试，我本地用的是 python 3.6，如果版本差别大可能会报错。如果报错，pip 安装一下 cython 模块，然后执行 `python setup.py build_ext --inplace` 自己编译一下。

**Comment by jewelc92** [comment]
> @jewelc92 你好，我刚上传了 compute_overlap 模块，你下载一下试试，我本地用的是 python 3.6，如果版本差别大可能会报错。如果报错，pip 安装一下 cython 模块，然后执行 `python setup.py build_ext --inplace` 自己编译一下。

**Comment by jewelc92** [comment]
感谢楼主，这个问题解决了，但是现在又出了新问题：
Traceback (most recent call last):
  File "train.py", line 488, in <module>
    main()
  File "train.py", line 448, in main
    config=args.config
  File "train.py", line 123, in create_models
    optimizer=keras.optimizers.adam(lr=lr)
  File "/home/wytj2/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 342, in compile
    sample_weight, mask)
  File "/home/wytj2/anaconda3/lib/python3.6/site-packages/keras/engine/training_utils.py", line 420, in weighted
    axis=list(range(weight_ndim, ndim)))
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by xuannianz** [comment]
你的 keras 是什么版本？ 我刚上传了 requirements.txt， 你看看依赖包的版本是不是一致。

**Comment by jewelc92** [comment]
> 你的 keras 是什么版本？ 我刚上传了 requirements.txt， 你看看依赖包的版本是不是一致。

更新了tensorflow版本果然可以了，再次感谢
