### ISSUE TITLE
Error occurs when using mobilenet backbone

### ISSUE THREAD

**Issue by JimLee1996** [xuannianz/keras-fcos#11]
Train model with mobilenet backbone,

```
python train.py --backbone mobilenet224_0.5 --gpu 1 --random-transform csv ../Mix_org/annotation.txt ../Mix_org/category.txt
```

and errors occured as:

```
......
Use tf.cast instead.
Epoch 1/50
Traceback (most recent call last):
  File "train.py", line 479, in <module>
    main()
  File "train.py", line 474, in main
    validation_data=validation_generator
  File "/home/icl/bin/python/envs/lpr/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/icl/bin/python/envs/lpr/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/icl/bin/python/envs/lpr/lib/python3.7/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/icl/bin/python/envs/lpr/lib/python3.7/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/icl/bin/python/envs/lpr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/icl/bin/python/envs/lpr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/icl/bin/python/envs/lpr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/icl/bin/python/envs/lpr/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Inputs to operation loss/classification_loss/Select_1 of type Select must have the same size and shape.  Input 0: [1,17884,2] != input 1: [1,17709,2]
         [[{{node loss/classification_loss/Select_1}}]]
         [[{{node loss/add_1}}]]
```

That seems the dimensions of y_true and y_pred dismatched when calculating losses.

**Comment by xuannianz** [comment]
Hi @JimLee1996 , only resnet* backbones work.

**Comment by JimLee1996** [comment]
Thanks for your apply.

So, what might be the reason for this error?
